#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.
#
# See also config/application.properties
#
isis:

  applib:
    annotation:
      action:
        command: ignore_safe
        publishing: none
      action-layout:
        css-class-fa:
          patterns:
            new.*:fa-plus,
            add.*:fa-plus-square,
            create.*:fa-plus,
            update.*:fa-edit,
            delete.*:fa-trash,
            find.*:fa-search,
            list.*:fa-list,
            all.*:fa-list
        css-class:
          patterns:
            delete.*:btn-danger
      domain-object:
        editing: false
        publishing: none
      property:
        command: all
        publishing: none
      property-layout:
        label-position: LEFT
      parameter-layout:
        label-position: LEFT

  core:
    meta-model:
      validator:
        allow-deprecated: false
        no-params-only: true
        explicit-logical-type-names: true
        service-actions-only: true
        mixins-only: true
      introspector:
        parallelize: false
        mode: full
        policy: ANNOTATION_REQUIRED
    runtime-services:
      translation:
        po:
          mode: disabled

  viewer:
    wicket:
      application:
        menubars-layout-xml: demoapp/dom/menubars.layout.xml
        favicon-url: images/gift.svg
        brand-logo-header: images/gift_48.png
        brand-logo-signin: images/gift_256.png
        name: Apache Isis Demo App
        # https://stackoverflow.com/a/38983935/56880
        # in addition using special config with the project's maven-resources-plugin
        version: ${project.version}
        css: css/application.css
        js: scripts/application.js
        about: This application demonstrates many aspects of the Apache Isis programming model, as well as some of the most significant domain services and extensions such as the WrapperFactory, security, commands and publishing.

      credit:
        - url:  http://isis.apache.org
          image: images/apache-isis/logo-48x48.png
          name: Apache Isis

      themes:
        initial: Flatly
        showChooser: true
        enabled: Cosmo,Flatly,Darkly,Sandstone,United

      max-title-length-in-standalone-tables: 0
      max-title-length-in-parented-tables: 0

      development-utilities:
        enable: false
      bookmarked-pages:
        show-chooser: true
        show-drop-down-on-footer: true
      dialog-mode: sidebar
      dialog-mode-for-menu: modal

# schema auto creation etc. ...
  persistence:
    schema:
       autoCreateSchemas: isisExtensionsSecman,demo

  extensions:
    secman:
      seed:
        admin:
          user-name: "sven"
          password: "pass"
          role-name: "isis-ext-secman-admin"
          namespace-permissions:
            sticky: "isis"
            additional: "demo"
        regular-user:
          role-name: "isis-ext-secman-user"
      permissionsEvaluationPolicy: ALLOW_BEATS_VETO

  testing:
    fixtures:
      fixture-scripts-specification:
        context-class: demoapp.dom._infra.fixtures.DemoFixtureScript
        multiple-execution-strategy: execute_once_by_value
        non-persisted-objects-strategy: ignore
        recreate: demoapp.dom._infra.fixtures.DemoFixtureScript
        run-script-default: demoapp.dom._infra.fixtures.DemoFixtureScript

# note that properties under 'datanucleus' must use camelCase rather than kebab-case
datanucleus:
  schema:
    validateTables: true
    validateConstraints: true

  persistenceByReachabilityAtCommit: false
  identifier:
    case: MixedCase

  cache:
    level2:
      type: none
      mode: ENABLE_SELECTIVE

resteasy:
  jaxrs:
    app:
      registration: beans
    defaultPath: "/restful"

server:
  http2:
    enabled: true
  max-http-header-size: 16KB
  servlet:
    session:
      timeout: 20m

spring:
  banner:
    location: banner.txt

  quartz:
    job-store-type: memory

vaadin:
  compatibilityMode: false
  whitelisted-packages: com.vaadin
  urlMapping: "/vaadin/*"
  servlet:
      productionMode: true

management:
  endpoint:
    health:
      enabled: true

