#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.
#
# See also config/application.properties
#
isis:

  applib:
    annotation:
      action:
        explicit: true
        publishing: none
      action-layout:
        css-class-fa:
          patterns:
            new.*:fa-plus,
            add.*:fa-plus-square,
            create.*:fa-plus,
            update.*:fa-edit,
            delete.*:fa-trash,
            find.*:fa-search,
            list.*:fa-list
        css-class:
          patterns:
            delete.*:btn-danger
      domain-object:
        editing: false
        publishing: none
      property:
        publishing: none
      property-layout:
        label-position: LEFT
      parameter-layout:
        label-position: LEFT

  core:
    meta-model:
      validator:
        allow-deprecated: false
        no-params-only: true
        explicit-object-type: true
        service-actions-only: true
        mixins-only: true
      introspector:
        parallelize: false
        mode: full
    runtime-services:
      translation:
        po:
          mode: disabled

  viewer:
    wicket:
      application:
        menubars-layout-xml: demoapp/dom/menubars.layout.xml
        favicon-url: images/favicon.png
        brand-logo-header: images/gift_48.png
        brand-logo-signin: images/gift_256.png
        name: Apache Isis Demo App
        css: css/application.css
        js: scripts/application.js
        about: Apache Isis Hello World

      credit:
        - url:  http://isis.apache.org
          image: images/apache-isis/logo-48x48.png
          name: Apache Isis

      themes:
        initial: Flatly
        showChooser: true
        enabled: Cosmo,Flatly,Darkly,Sandstone,United

      max-title-length-in-standalone-tables: 0
      max-title-length-in-parented-tables: 0

      development-utilities:
        enable: false
      bookmarked-pages:
        show-chooser: true
        show-drop-down-on-footer: true
      dialog-mode: sidebar
      dialog-mode-for-menu: modal

  persistence:
    jdo-datanucleus:
      impl:
        # note that properties under 'isis.persistor.datanucleus.impl' are passed through directly
        # to DataNucleus, and must use camelCase rather than kebab-case
        datanucleus:
          schema:
            validateTables: true
            validateConstraints: true

          persistenceByReachabilityAtCommit: false
          identifier:
            case: MixedCase

          cache:
            level2:
              type: none
              mode: ENABLE_SELECTIVE

resteasy:
  jaxrs:
    app:
      registration: beans
    defaultPath: "/restful"

server:
  max-http-header-size: 16KB

spring:
  banner:
    location: banner.txt

  quartz:
    job-store-type: memory

vaadin:
  compatibilityMode: false
  whitelisted-packages: com.vaadin
  urlMapping: "/vaadin/*"
  servlet:
      productionMode: true

management:
  endpoint:
    health:
      enabled: true
