image: maven:3.6.2-jdk-11

stages:
  - build-package-push

variables:
  BASELINE: 2.0.0-M2
  
include:
  - local: scripts/ci/core-gitlab-ci.yml

before_script:
  - export PROJECT_ROOT_PATH=$CI_PROJECT_DIR
  - export CI_SCRIPTS_PATH=$PROJECT_ROOT_PATH/scripts/ci
  - export REVISION=$BASELINE.$(date +%Y%m%d)-$(date +%H%M)-$(echo $CI_COMMIT_SHA | cut -c1-8)
