#
# This script:
#
# - builds snapshot of isis
#   - pushes to repo.incode.work
#   - pushes to repo.incode.cloud
# - builds Docker image of simpleapp
#   -  pushes to hub.docker.com
#
#
# It requires the following gitlab secret variables
#
# - GCPAPPENGINEREPO_USERNAME
# - GCPAPPENGINEREPO_PASSWORD
# - GCPAPPENGINEREPO_URL
#
# - DOCKER_REGISTRY_USERNAME    # eg "apacheisiscommitters"  (needs to be in the ORG_NAME)
# - DOCKER_REGISTRY_EMAIL
# - DOCKER_REGISTRY_PASSWORD
# - DOCKER_REGISTRY_URL         # eg "https://index.docker.io/v1/"
#
# NB: if deploying to docker hub, then the image is named apacheisis/$APPNAME,
#     where 'apacheisis' is an org that the user can write to
#
#     Use $DOCKER_REGISTRY_USERNAME/$DOCKER_REGISTRY_PASSWORD credentials to upload
#

image: maven:3.5.3-jdk-8

before_script:
  - export BASELINE=2.0.0-M2
  - export REVISION=$BASELINE.$(date +%Y%m%d)-$(date +%H%M)-$(echo $CI_COMMIT_SHA | cut -c1-8)

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  ORG_NAME: "apacheisis"
  APP_NAME: "simpleapp"

stages:
  - build-package-push

build-package-push:
  stage: build-package-push
  script:
    - echo ""
    - echo ""
    - echo ""
    - echo "$REVISION"
    - echo "GCPAPPENGINEREPO_URL=$GCPAPPENGINEREPO_URL"
    - echo ""
    - echo ""
    - echo ""
    - cd core
    - >
      mvn -s .m2/settings.xml \
          --batch-mode \
          clean deploy \
          -Dgcpappenginerepo-deploy \
          -Dgcpappenginerepo-deploy.repositoryUrl=$GCPAPPENGINEREPO_URL \
          -Drevision=$REVISION \
          -Dskip.assemble-zip \
          -Dskip.mavenmixin-standard \
          -Dskip.mavenmixin-docker \
          -Dskip.mavenmixin-surefire \
          -Dskip.mavenmixin-datanucleus-enhance \
          $CORE_ADDITIONAL_OPTS
    - cd ..
    - echo ""
    - echo ""
    - echo ""
    - echo "$REVISION"
    - echo ""
    - echo ""
    - echo ""
    - cd examples/apps/$APP_NAME
    - >
      mvn --batch-mode \
          install \
          -Drevision=$REVISION \
          -Disis.version=$REVISION \
          $CORE_ADDITIONAL_OPTS \
          -Dmavenmixin-docker \
          -Ddocker-plugin.imageName=$ORG_NAME/$APP_NAME
    - >
      mvn -s .m2/settings.xml \
          --batch-mode \
          docker:push@push-image-tagged \
          -pl webapp \
          -DskipTests \
          -Dskip.isis-validate \
          -Dskip.isis-swagger \
          -Drevision=$REVISION \
          -Disis.version=$REVISION \
          -Dmavenmixin-docker \
          -Ddocker-plugin.imageName=$ORG_NAME/$APP_NAME \
          -Ddocker-plugin.serverId=docker-registry \
          -Ddocker.registryUrl=$DOCKER_REGISTRY_URL
    - cd ../../..


#
# Previously this script also uploaded to a Sonatype Nexus.
# Here's the stuff that did it.
#
# It requires the following gitlab secret variables
#
# - NEXUS_USERNAME
# - NEXUS_PASSWORD
# - NEXUS_REPO_URL
#
#    - cd core
#    - >
#      mvn -s .m2/settings.xml \
#          --batch-mode \
#          clean deploy \
#          -Drevision=$REVISION \
#          -Dnexus-deploy \
#          -Dnexus-deploy.repositoryUrl=$NEXUS_REPO_URL \
#          $CORE_ADDITIONAL_OPTS
#    - cd ..