site:
  title: Apache Isis
  url: https://isis.apache.org/
  start_page: toc:ROOT:about.adoc

content:
  sources:

# antora
    - url: .
      start_path: antora/components/toc # toc
      branches: HEAD

    - url: .
      start_path: antora/components/incubator # incubator
      branches: HEAD

# incubator
    - url: .
<<<<<<< HEAD
      start_path: incubator/core/model/src/main/doc # incubator
      branches: HEAD
    - url: .
      start_path: incubator/mappings/microprofile/src/main/doc # incubator
=======
      start_path: incubator/extensions/core/model/src/main/adoc # incubator
      branches: HEAD
    - url: .
      start_path: incubator/extensions/core/microprofile/src/main/adoc # incubator
>>>>>>> ISIS-2062: moves src/main/doc to src/main/adoc
      branches: HEAD


ui:
  bundle:
    url: ../isis-antora/build/ui-bundle.zip
#    url: https://github.com/apache/isis-antora/blob/master/build/ui-bundle.zip?raw=true
    #url: ./antora/theme/ui-bundle.zip
    snapshot: true
  supplemental_files: antora/supplemental-ui

asciidoc:
  extensions:
    - asciidoctor-plantuml
    - ./antora/lib/lorem
    - ./antora/lib/jira-issue
    - ./antora/lib/powershell
  attributes:
    experimental: ""
    idprefix: ""
    idseparator: "-"
    plantuml-server-url: "http://www.plantuml.com/plantuml"
    isiscurr: "2.0.0-M2"
    isisnext: "2.0.0-M3"
    isisnextafter: "2.0.0-M4"
    :isisdevafter: "2.0.0-M4-SNAPSHOT"

output:
  dir: antora/target/site
