site:
  title: Apache Isis
  url: https://isis.apache.org/
  start_page: toc:ROOT:about.adoc

content:
  sources:

# antora
    - url: .
      start_path: antora/components/toc # toc
      branches: HEAD

    - url: .
      start_path: antora/components/extensions # extensions
      branches: HEAD

# extensions
    - url: .
      start_path: extensions/persistence/flywayjdo/src/main/adoc # extensions
      branches: HEAD

    - url: .
      start_path: extensions/security/secman/src/main/adoc # security
      branches: HEAD
    - url: .
      start_path: extensions/security/secman/api/src/main/adoc # security
      branches: HEAD
    - url: .
      start_path: extensions/security/secman/encryption-jbcrypt/src/main/adoc # security
      branches: HEAD
    - url: .
      start_path: extensions/security/secman/model/src/main/adoc # security
      branches: HEAD
    - url: .
      start_path: extensions/security/secman/persistence-jdo/src/main/adoc # security
      branches: HEAD
    - url: .
      start_path: extensions/security/secman/shiro-realm/src/main/adoc # security
      branches: HEAD
    - url: .
      start_path: extensions/security/shiro-realm-ldap/src/main/adoc # security
      branches: HEAD

    - url: .
      start_path: extensions/vro/cors/src/main/adoc # vro
      branches: HEAD
    - url: .
      start_path: extensions/vw/exceldownload/src/main/adoc # vw
      branches: HEAD
    - url: .
      start_path: extensions/vw/pdfjs/src/main/adoc # vw
      branches: HEAD


ui:
  bundle:
    url: ../isis-antora/build/ui-bundle.zip
#    url: https://github.com/apache/isis-antora/blob/master/build/ui-bundle.zip?raw=true
    #url: ./antora/theme/ui-bundle.zip
    snapshot: true
  supplemental_files: antora/supplemental-ui

asciidoc:
  extensions:
    - asciidoctor-plantuml
    - ./antora/lib/lorem
    - ./antora/lib/jira-issue
    - ./antora/lib/powershell
  attributes:
    experimental: ""
    idprefix: ""
    idseparator: "-"
    plantuml-server-url: "http://www.plantuml.com/plantuml"
    isiscurr: "2.0.0-M2"
    isisnext: "2.0.0-M3"
    isisnextafter: "2.0.0-M4"
    :isisdevafter: "2.0.0-M4-SNAPSHOT"

output:
  dir: antora/target/site
