site:
  title: Apache Isis
  url: https://isis.apache.org/
  start_page: toc:ROOT:about.adoc

content:
  sources:

# antora
    - url: .
      start_path: antora/components/extensions # other
      branches: HEAD
    - url: .
      start_path: antora/components/incubator # other
      branches: HEAD
    - url: .
      start_path: antora/components/legacy # other
      branches: HEAD
    - url: .
      start_path: antora/components/toc
      branches: HEAD

# incubator
    - url: .
      start_path: incubator/core/model/src/main/doc # other
      branches: HEAD

# legacy
    - url: .
      start_path: legacy/core/applib/src/main/doc # other
      branches: HEAD
    - url: .
      start_path: legacy/core/commons/src/main/doc # other
      branches: HEAD
    - url: .
      start_path: legacy/core/runtime/src/main/doc # other
      branches: HEAD

# extensions
    - url: .
      start_path: extensions/core/spring/src/main/doc # other
      branches: HEAD


ui:
  bundle:
    url: ../isis-antora/build/ui-bundle.zip
#    url: https://github.com/apache/isis-antora/blob/master/build/ui-bundle.zip?raw=true
    #url: ./antora/theme/ui-bundle.zip
    snapshot: true
  supplemental_files: antora/supplemental-ui

asciidoc:
  extensions:
    - asciidoctor-plantuml
    - ./antora/lib/lorem
    - ./antora/lib/jira-issue
    - ./antora/lib/powershell
  attributes:
    experimental: ""
    idprefix: ""
    idseparator: "-"
    plantuml-server-url: "http://www.plantuml.com/plantuml"
    isiscurr: "2.0.0-M2"
    isisnext: "2.0.0-M3"
    isisnextafter: "2.0.0-M4"
    :isisdevafter: "2.0.0-M4-SNAPSHOT"

output:
  dir: antora/target/site
