site:
  title: Apache Isis
  url: https://isis.apache.org/
  start_page: toc:ROOT:about.adoc

content:
  sources:

# antora
    - url: .
      start_path: antora/components/toc # toc
      branches: HEAD

    - url: .
      start_path: antora/components/core # core
      branches: HEAD
    - url: .
      start_path: antora/components/extensions # extensions
      branches: HEAD
    - url: .
      start_path: antora/components/incubator # incubator
      branches: HEAD
    - url: .
      start_path: antora/components/legacy # legacy
      branches: HEAD
    - url: .
      start_path: antora/components/mappings # mappings
      branches: HEAD
    - url: .
      start_path: antora/components/refguide # refguide
      branches: HEAD
    - url: .
      start_path: antora/components/security # security
      branches: HEAD
    - url: .
      start_path: antora/components/subdomains # subdomains
      branches: HEAD
    - url: .
      start_path: antora/components/testing # testing
      branches: HEAD
    - url: .
      start_path: antora/components/userguide # userguide
      branches: HEAD
    - url: .
      start_path: antora/components/valuetypes # valuetypes
      branches: HEAD

# api
    - url: .
      start_path: api/applib/src/main/doc # refguide
      branches: HEAD
    - url: .
      start_path: api/schema/src/main/doc # refguide
      branches: HEAD

# core
    - url: .
      start_path: core/codegen-bytebuddy/src/main/doc # core
      branches: HEAD
    - url: .
      start_path: core/commons/src/main/doc # core
      branches: HEAD
    - url: .
      start_path: core/config/src/main/doc # refguide
      branches: HEAD
    - url: .
      start_path: core/detached-tests/src/main/doc # core
      branches: HEAD
    - url: .
      start_path: core/metamodel/src/main/doc # core
      branches: HEAD
    - url: .
      start_path: persistence/jdo/src/main/doc # pjdo
      branches: HEAD
    - url: .
      start_path: core/runtime/src/main/doc # core
      branches: HEAD
    - url: .
      start_path: core/webspringboot/src/main/doc # core
      branches: HEAD
    - url: .
      start_path: core/runtimeservices/src/main/doc # core
      branches: HEAD
    - url: .
      start_path: core/webapp/src/main/doc # core
      branches: HEAD
    - url: .
      start_path: core/security/src/main/doc # security
      branches: HEAD
    - url: .
      start_path: unittestsupport/src/main/doc # testing
      branches: HEAD
    - url: .
      start_path: viewers/restfulobjects/jaxrs-resteasy-4/src/main/doc # vro
      branches: HEAD
    - url: .
      start_path: viewers/restfulobjects/src/main/doc # vro
      branches: HEAD
    - url: .
      start_path: viewers/wicket/src/main/doc # vw
      branches: HEAD

# examples
    - url: .
      start_path: examples/demo/src/main/doc # demoapp
      branches: HEAD
    - url: .
      start_path: examples/smoketests/src/main/doc # core
      branches: HEAD

# extensions
    - url: .
      start_path: extensions/persistence/jdo/flywayjdo/src/main/doc # extensions
      branches: HEAD

    - url: .
      start_path: extensions/security/secman/src/main/doc # security
      branches: HEAD
    - url: .
      start_path: extensions/security/shiro-realm-ldap/src/main/doc # security
      branches: HEAD

    - url: .
      start_path: extensions/vro/cors/src/main/doc # vro
      branches: HEAD
    - url: .
      start_path: extensions/vw/exceldownload/src/main/doc # vw
      branches: HEAD
    - url: .
      start_path: extensions/vw/pdfjs/src/main/doc # vw
      branches: HEAD

# incubator
    - url: .
      start_path: incubator/extensions/core/model/src/main/doc # incubator
      branches: HEAD
    - url: .
      start_path: incubator/extensions/core/microprofile/src/main/doc # incubator
      branches: HEAD

# legacy
    - url: .
      start_path: legacy/extensions/core/applib/src/main/doc # legacy
      branches: HEAD
    - url: .
      start_path: legacy/extensions/core/commons/src/main/doc # legacy
      branches: HEAD
    - url: .
      start_path: legacy/extensions/core/runtime/src/main/doc # legacy
      branches: HEAD
    - url: .
      start_path: legacy/mappings/restclient/src/main/doc # legacy
      branches: HEAD
    - url: .
      start_path: legacy/subdomains/servletapi/impl/src/main/doc # legacy
      branches: HEAD

# mappings
    - url: .
      start_path: mappings/jaxrsclient/src/main/doc # mappings
      branches: HEAD
    - url: .
      start_path: mappings/minio/src/main/doc # mappings
      branches: HEAD
    - url: .
      start_path: mappings/restclient/src/main/doc # mappings
      branches: HEAD
    - url: .
      start_path: mappings/slack/src/main/doc # mappings
      branches: HEAD

# mavendeps
    - url: .
      start_path: mavendeps/src/main/doc # toc
      branches: HEAD

# security
    - url: .
      start_path: security/bypass/src/main/doc # security
      branches: HEAD
    - url: .
      start_path: security/shiro/src/main/doc # security
      branches: HEAD
    - url: .
      start_path: security/keycloak/src/main/doc # security
      branches: HEAD

# starters
    - url: .
      start_path: starters/src/main/doc # toc
      branches: HEAD

# subdomains
    - url: .
      start_path: subdomains/base/src/main/doc # subdomains
      branches: HEAD
    - url: .
      start_path: subdomains/docx/src/main/doc # subdomains
      branches: HEAD
    - url: .
      start_path: subdomains/excel/src/main/doc # subdomains
      branches: HEAD
    - url: .
      start_path: subdomains/freemarker/src/main/doc # subdomains
      branches: HEAD
    - url: .
      start_path: subdomains/ognl/src/main/doc # subdomains
      branches: HEAD
    - url: .
      start_path: subdomains/pdfbox/src/main/doc # subdomains
      branches: HEAD
    - url: .
      start_path: subdomains/spring/src/main/doc # subdomains
      branches: HEAD
    - url: .
      start_path: subdomains/xdocreport/src/main/doc # subdomains
      branches: HEAD
    - url: .
      start_path: subdomains/zip/src/main/doc # subdomains
      branches: HEAD

# testing
    - url: .
      start_path: testing/fakedata/src/main/doc # testing
      branches: HEAD
    - url: .
      start_path: testing/fixtures/src/main/doc # testing
      branches: HEAD
    - url: .
      start_path: testing/h2console/src/main/doc # testing
      branches: HEAD
    - url: .
      start_path: testing/hsqldbmgr/src/main/doc # testing
      branches: HEAD
    - url: .
      start_path: testing/integtestsupport/src/main/doc # testing
      branches: HEAD
    - url: .
      start_path: testing/specsupport/src/main/doc # testing
      branches: HEAD
    - url: .
      start_path: testing/unittestsupport/src/main/doc # testing
      branches: HEAD

# valuetypes
    - url: .
      start_path: valuetypes/asciidoc/src/main/doc # vw
      branches: HEAD
    - url: .
      start_path: valuetypes/markdown/src/main/doc # vw
      branches: HEAD
    - url: .
      start_path: valuetypes/sse/src/main/doc # vw
      branches: HEAD

ui:
  bundle:
#    url: ../isis-antora/build/ui-bundle.zip
    url: https://github.com/apache/isis-antora/blob/master/build/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: antora/supplemental-ui

asciidoc:
  extensions:
    - asciidoctor-plantuml
    - ./antora/lib/lorem
    - ./antora/lib/jira-issue
    - ./antora/lib/powershell
  attributes:
    experimental: ""
    idprefix: ""
    idseparator: "-"
    plantuml-server-url: "http://www.plantuml.com/plantuml"
    isiscurr: "2.0.0-M2"
    isisnext: "2.0.0-M3"
    isisnextafter: "2.0.0-M4"
    :isisdevafter: "2.0.0-M4-SNAPSHOT"

output:
  dir: antora/target/site
