site:
  title: Apache Isis
  url: https://isis.apache.org/
  start_page: toc:ROOT:about.adoc

content:
  sources:

# antora
    - url: .
      start_path: antora/components/toc # toc
      branches: HEAD

    - url: .
      start_path: antora/components/subdomains # subdomains
      branches: HEAD

    # subdomains
    - url: .
      start_path: subdomains/base/src/main/doc # subdomains
      branches: HEAD
    - url: .
      start_path: subdomains/docx/src/main/doc # subdomains
      branches: HEAD
    - url: .
      start_path: subdomains/excel/impl/src/main/doc # subdomains
      branches: HEAD
    - url: .
      start_path: subdomains/freemarker/impl/src/main/doc # subdomains
      branches: HEAD
    - url: .
      start_path: subdomains/ognl/impl/src/main/doc # subdomains
      branches: HEAD
    - url: .
      start_path: subdomains/pdfbox/impl/src/main/doc # subdomains
      branches: HEAD
    - url: .
      start_path: subdomains/spring/impl/src/main/doc # subdomains
      branches: HEAD
    - url: .
      start_path: subdomains/xdocreport/impl/src/main/doc # subdomains
      branches: HEAD
    - url: .
      start_path: subdomains/zip/impl/src/main/doc # subdomains
      branches: HEAD



ui:
  bundle:
    url: ../isis-antora/build/ui-bundle.zip
#    url: https://github.com/apache/isis-antora/blob/master/build/ui-bundle.zip?raw=true
    #url: ./antora/theme/ui-bundle.zip
    snapshot: true
  supplemental_files: antora/supplemental-ui

asciidoc:
  extensions:
    - asciidoctor-plantuml
    - ./antora/lib/lorem
    - ./antora/lib/jira-issue
    - ./antora/lib/powershell
  attributes:
    experimental: ""
    idprefix: ""
    idseparator: "-"
    plantuml-server-url: "http://www.plantuml.com/plantuml"
    isiscurr: "2.0.0-M2"
    isisnext: "2.0.0-M3"
    isisnextafter: "2.0.0-M4"
    :isisdevafter: "2.0.0-M4-SNAPSHOT"

output:
  dir: antora/target/site
