#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.

site:
  title: Apache Causeway
  url: https://causeway.apache.org/
  start_page: docs:ROOT:about.adoc

content:
  sources:

# antora
    - url: .
      start_path: antora/components/docs # docs
      branches: HEAD
    - url: .
      start_path: antora/components/comguide # comguide
      branches: HEAD
    - url: .
      start_path: antora/components/conguide # conguide
      branches: HEAD
    - url: .
      start_path: antora/components/relnotes # relnotes
      branches: HEAD
    - url: .
      start_path: antora/components/setupguide # setupguide
      branches: HEAD
    - url: .
      start_path: antora/components/refguide # refguide
      branches: HEAD
    - url: .
      start_path: antora/components/refguide-index # refguide
      branches: HEAD
    - url: .
      start_path: antora/components/userguide # userguide
      branches: HEAD

# api
    - url: .
      start_path: api/schema/src/main/adoc # refguide
      branches: HEAD

# core
    - url: .
      start_path: core/adoc  # core (design docs)
      branches: HEAD
    - url: .
      start_path: core/codegen-bytebuddy/src/main/adoc # core
      branches: HEAD
    - url: .
      start_path: commons/src/main/adoc # core
      branches: HEAD
    - url: .
      start_path: core/config/src/main/adoc # refguide
      branches: HEAD
    - url: .
      start_path: core/interaction/src/main/adoc # core
      branches: HEAD
    - url: .
      start_path: core/internaltestsupport/src/main/adoc # core
      branches: HEAD
    - url: .
      start_path: core/metamodel/src/main/adoc # core
      branches: HEAD
    - url: .
      start_path: core/runtime/src/main/adoc # core
      branches: HEAD
    - url: .
      start_path: core/runtimeservices/src/main/adoc # core
      branches: HEAD
    - url: .
      start_path: core/security/src/main/adoc # security
      branches: HEAD
    - url: .
      start_path: core/transaction/src/main/adoc # core
      branches: HEAD
    - url: .
      start_path: core/webapp/src/main/adoc # core
      branches: HEAD

# examples
    - url: .
      start_path: examples/demo/domain/src/main/adoc # docs
      branches: HEAD
    - url: .
      start_path: antora/components/tutorials # tutorials
      branches: HEAD

# extensions
    - url: .
      start_path: extensions/adoc # extensions
      branches: HEAD

    - url: .
      start_path: extensions/core/commandlog/adoc # userguide
      branches: HEAD
    - url: .
      start_path: extensions/core/excel/adoc # userguide
      branches: HEAD
    - url: .
      start_path: extensions/core/executionlog/adoc # userguide
      branches: HEAD
    - url: .
      start_path: extensions/core/executionoutbox/adoc # userguide
      branches: HEAD
    - url: .
      start_path: extensions/core/executionrepublisher/adoc # userguide
      branches: HEAD
    - url: .
      start_path: extensions/core/flyway/adoc # userguide
      branches: HEAD

    - url: .
      start_path: extensions/security/audittrail/adoc # security
      branches: HEAD
    - url: .
      start_path: extensions/security/secman/adoc # security
      branches: HEAD
    - url: .
      start_path: extensions/security/sessionlog/adoc # security
      branches: HEAD
    - url: .
      start_path: extensions/security/shiro-realm-ldap/adoc # security
      branches: HEAD
    - url: .
      start_path: extensions/security/spring-oauth2/src/main/adoc # security
      branches: HEAD

    - url: .
      start_path: extensions/vro/cors/adoc # vro
      branches: HEAD

    - url: .
      start_path: extensions/vw/exceldownload/adoc # vw
      branches: HEAD
    - url: .
      start_path: extensions/vw/fullcalendar/adoc # vw
      branches: HEAD
    - url: .
      start_path: extensions/vw/pdfjs/adoc # vw
      branches: HEAD
    - url: .
      start_path: extensions/vw/sse/adoc # vw
      branches: HEAD

# incubator
    - url: .
      start_path: incubator/adoc # incubator
      branches: HEAD
    - url: .
      start_path: incubator/clients/kroviz/adoc # incubator
      branches: HEAD
    - url: .
      start_path: incubator/extensions/core/commandreplay/adoc # incubator
      branches: HEAD
    - url: .
      start_path: incubator/viewers/graphql/adoc # incubator
      branches: HEAD
#    - url: .
#      start_path: incubator/viewers/javafx/adoc # incubator
#      branches: HEAD
    - url: .
      start_path: incubator/viewers/vaadin/adoc # incubator
      branches: HEAD

# mavendeps
    - url: .
      start_path: mavendeps/adoc # starters
      branches: HEAD

# persistence
    - url: .
      start_path: persistence/jpa/adoc # pjpa
      branches: HEAD
    - url: .
      start_path: persistence/jdo/adoc # pjdo
      branches: HEAD

# regression tests
    - url: .
      start_path: regressiontests/adoc # regressiontests
      branches: HEAD

# security
    - url: .
      start_path: security/adoc # security
      branches: HEAD
    - url: .
      start_path: security/bypass/src/main/adoc # security
      branches: HEAD
    - url: .
      start_path: security/shiro/src/main/adoc # security
      branches: HEAD
    - url: .
      start_path: security/keycloak/src/main/adoc # security
      branches: HEAD
    - url: .
      start_path: security/spring/src/main/adoc # security
      branches: HEAD

# starters
    - url: .
      start_path: starters/adoc # toc
      branches: HEAD


# testing
    - url: .
      start_path: testing/adoc # testing
      branches: HEAD
    - url: .
      start_path: testing/archtestsupport/adoc # testing
      branches: HEAD
    - url: .
      start_path: testing/fakedata/adoc # testing
      branches: HEAD
    - url: .
      start_path: testing/fixtures/adoc # testing
      branches: HEAD
    - url: .
      start_path: testing/h2console/adoc # testing
      branches: HEAD
    - url: .
      start_path: testing/hsqldbmgr/adoc # testing
      branches: HEAD
    - url: .
      start_path: testing/integtestsupport/adoc # testing
      branches: HEAD
    - url: .
      start_path: testing/specsupport/adoc # testing
      branches: HEAD
    - url: .
      start_path: testing/unittestsupport/adoc # testing
      branches: HEAD

# tooling
    - url: .
      start_path: tooling/adoc # toc
      branches: HEAD
    - url: .
      start_path: tooling/cli/adoc # cli
      branches: HEAD

# valuetypes
    - url: .
      start_path: valuetypes/adoc # valuetypes
      branches: HEAD
    - url: .
      start_path: valuetypes/asciidoc/adoc # valuetypes
      branches: HEAD
#    - url: .
#      start_path: valuetypes/jodatime/adoc # valuetypes
#      branches: HEAD
    - url: .
      start_path: valuetypes/markdown/adoc # valuetypes
      branches: HEAD
    - url: .
      start_path: valuetypes/vega/adoc # valuetypes
      branches: HEAD

# viewers
    - url: .
      start_path: viewers/restfulobjects/adoc # vro
      branches: HEAD
    - url: .
      start_path: viewers/wicket/adoc # vw
      branches: HEAD


ui:
  bundle:
#    url: ../causeway-antora/build/ui-bundle.zip
    url: https://github.com/apache/isis-antora/blob/master/build/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: antora/supplemental-ui

asciidoc:
  extensions:
    - asciidoctor-kroki # requires: npm i ... @asciidoctor/core@2.2.0 asciidoctor-kroki
#    - asciidoctor-plantuml # requires: npm i ... asciidoctor-plantuml@1.5.0
    - ./antora/lib/lorem
    - ./antora/lib/jira-issue
  attributes:
    experimental: ""
    idprefix: ""
    idseparator: "-"
    # kroki
    # for more options see https://github.com/Mogztter/asciidoctor-kroki
    kroki-default-format: svg # (default)
    kroki-default-options: interactive # only available for SVG
    kroki-fetch-diagram: true
    kroki-server-url: https://kroki.io # (default)
    page-causewayprev: "2.0.0-M9"
    page-causewayrel: "2.0.0-RC1"

output:
  dir: antora/target/site
