site:
  title: Apache Isis
  url: https://isis.apache.org/
  start_page: toc:ROOT:about.adoc

content:
  sources:

# antora
    - url: .
      start_path: antora/components/toc # toc
      branches: HEAD

    - url: .
      start_path: antora/components/core # core
      branches: HEAD

# core
    - url: .
      start_path: core/codegen-bytebuddy/src/main/adoc # core
      branches: HEAD
    - url: .
      start_path: core/commons/src/main/adoc # core
      branches: HEAD
    - url: .
      start_path: core/detached-tests/src/main/adoc # core
      branches: HEAD
    - url: .
      start_path: core/metamodel/src/main/adoc # core
      branches: HEAD
    - url: .
      start_path: core/runtime/src/main/adoc # core
      branches: HEAD
    - url: .
<<<<<<< HEAD
      start_path: core/runtimeservices/src/main/doc # core
=======
      start_path: core/webspringboot/src/main/adoc # core
      branches: HEAD
    - url: .
      start_path: core/runtimeservices/src/main/adoc # core
>>>>>>> ISIS-2062: moves src/main/doc to src/main/adoc
      branches: HEAD
    - url: .
      start_path: core/webapp/src/main/adoc # core
      branches: HEAD

# examples
    - url: .
      start_path: examples/smoketests/src/main/adoc # core
      branches: HEAD

ui:
  bundle:
    url: ../isis-antora/build/ui-bundle.zip
#    url: https://github.com/apache/isis-antora/blob/master/build/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: antora/supplemental-ui

asciidoc:
  extensions:
    - asciidoctor-plantuml
    - ./antora/lib/lorem
    - ./antora/lib/jira-issue
    - ./antora/lib/powershell
  attributes:
    experimental: ""
    idprefix: ""
    idseparator: "-"
    plantuml-server-url: "http://www.plantuml.com/plantuml"
    isiscurr: "2.0.0-M2"
    isisnext: "2.0.0-M3"
    isisnextafter: "2.0.0-M4"
    :isisdevafter: "2.0.0-M4-SNAPSHOT"

output:
  dir: antora/target/site
