isis:
  reflector:
    validator:
      allowDeprecated: false
      noParamsOnly: true
      explicitObjectType: true
      serviceActionsOnly: true
      mixinsOnly: true

    facet:
      cssClassFa:
        patterns:
          new.*:fa-plus,\
          add.*:fa-plus-square,\
          create.*:fa-plus,\
          update.*:fa-edit,\
          delete.*:fa-trash,\
          find.*:fa-search,\
          list.*:fa-list

      cssClass:
        patterns:
          delete.*:btn-danger

  objects:
    editing: false

  viewer:
    wicket:
      application:
        name: Hello World App
        css: css/application.css
        js: scripts/application.js
        about: Hello World
      welcome:
        file: welcome.html

      credit[0]:
        image: /images/apache-isis/logo-48x48.png
        name: Apache Isis
        url: http://isis.apache.org

      themes:
        initial: Flatly
        showChooser: true
        enabled: Cosmo,Flatly,Darkly,Sandstone,United

      maxTitleLengthInStandaloneTables: 0
      maxTitleLengthInParentedTables: 0

  persistor:
    datanucleus:
      impl:
        datanucleus:
          schema:
            validateTables: true
            validateConstraints: true

          persistenceByReachabilityAtCommit: false
          identifier:
            case: MixedCase

          cache:
            level2:
              type: none
              mode: ENABLE_SELECTIVE
